# Generated by Django 2.2.16 on 2022-03-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Аутентифицированный пользователь'), ('MODERATOR', 'Модератор'), ('ADMIN', 'Администратор')], default='USER', max_length=50, verbose_name='role'),
        ),
    ]
