# Generated by Django 2.2.16 on 2022-03-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.CharField(default=1, max_length=256, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
